### ISSUE TITLE
Porque não aparece o ID do restaurante no objeto do produto quando incluimos um item na Sacola?

### ISSUE THREAD

**Issue by luizh-silva-oliveira** [cami-la/sacola-api_IFOOD_DEV_WEEK#31]
![image](https://user-images.githubusercontent.com/41453112/193918474-800ac73c-ecc1-41ee-afd6-2cfda0521161.png)

![image](https://user-images.githubusercontent.com/41453112/193918352-e5a2b77a-7c4e-428d-bbf3-d7a32cee4fcf.png)

**Comment by cami-la** [comment]
Oi, @Luizifpb. Tudo bem?
Então, é por conta do relacionamento das classes `@ManyToOne`. É um comportamento padrão desse tipo de relacionamento.
Caso você quisesse ver as informações completas do `Produto`, aí você poderia criar um endpoint para retornar essas informações.

**Comment by luizh-silva-oliveira** [comment]
Show, muito obrigado Camila!!
