### ISSUE TITLE
Mudar diretório da aplicação

### ISSUE THREAD

**Issue by satirioneto** [cami-la/sacola-api_IFOOD_DEV_WEEK#34]
Oi Camila!

Queria mudar o diretório da aplicação mas fazendo isso com Copiar/Colar eu não consigo executar a aplicação. Como posso fazer isso?

**Comment by cami-la** [comment]
Você pode pegar o projeto inteiro e colocar em outra pasta.
Ou iniciar o projeto novamente, porque os arquivos de configuração fica vinculado ao diretório onde está o projeto.
