### ISSUE TITLE
erro ao importar o swagger

### ISSUE THREAD

**Issue by JacksonJeanPS** [cami-la/sacola-api_IFOOD_DEV_WEEK#35]
1- Caused by: java.lang.NullPointerException: Cannot invoke "org.springframework.web.servlet.mvc.condition.PatternsRequestCondition.getPatterns()" because "this.condition" is null

2- Execution failed for task ':SacolaApiApplication.main()'.

Process 'command 'C:/Users/Jackson/.jdks/azul-17.0.4.1/bin/java.exe'' finished with non-zero exit value 1

Antes de adicionar o implementation 'io.springfox:springfox-boot-starter:3.0.0' não dava erro, e agora fica dando erro.

Como corrigir.

Já reinstalei, já mudei o jdk, ja baixei o arquivo zulu de novo, ja fechei e abri, já reiniciei, já dei ctrl c + ctrl v nos arquivos aqui no git. e nada de corrigir. ME HELPAAAAAA

**Comment by cami-la** [comment]
Oi, @JacksonJeanPS. Tudo bem?
Então, não sei se você já conseguiu resolver esse probleminha, mas tem uma issue de um colega que estava com a mesma dúvida que você, segue a issue: https://github.com/cami-la/sacola-api_IFOOD_DEV_WEEK/issues/16#issuecomment-1264342500
