### ISSUE TITLE
Não consigo rodar o programa inicial

### ISSUE THREAD

**Issue by BrunoFico** [cami-la/sacola-api_IFOOD_DEV_WEEK#4]
Não estou conseguindo roda a 1ª vez, assim que abrimos o projeto. Eu faço a abertura do arquivo do Spring io > Clico em Build > depois abro o SacolaApiApplication e vou em Run... pronto ele já da erro ai, conforme print abaixo... não consigo sair daqui. Coloquei outras prints das configurações de Project Structure, não sei se tem influencia...
![PRINT ERRO](https://user-images.githubusercontent.com/113647995/193048766-a7899153-6b85-46a9-a72f-96c596fbb80f.png)
![PRINT GRADLE](https://user-images.githubusercontent.com/113647995/193048771-14d347bb-fc37-4cd7-8353-ddd15f940a79.png)
![PROJECT STRUCTURE - 2](https://user-images.githubusercontent.com/113647995/193048772-0654250a-f5e4-4aac-b4fc-174b81671b3f.png)
![PROJECT STRUCTURE](https://user-images.githubusercontent.com/113647995/193048778-ee7c1aba-f9df-4002-a5ff-9f36543b840c.png)

**Comment by cami-la** [comment]
Oi, amigo. Tudo bem?
Pelo visto está tudo certo nas suas configurações. 
Clica nessa linha que estou indicando e me mostra o erro que apareceu:

![2022-09-29_18-47](https://user-images.githubusercontent.com/64323124/193148213-d8c794ae-a39f-4a5a-ac65-30710e6c2f56.png)

**Comment by BrunoFico** [comment]
Oie, tudo ótimo e com você ?

Olha, eu fiz do zero de novo e agora foi kkk ele fica rodando mas da Starter, acho que é isso né ? (mas tipo, ja fazem 30min que ta rodando)

Mas ai, apareceu isso agora, na parte do LocalHost:
![image](https://user-images.githubusercontent.com/113647995/193160875-8c26d7c3-0fda-4c68-ba74-f0a680c78a55.png)

**Comment by BrunoFico** [comment]
Oie, tudo ótimo e com você ?

Olha, eu fiz do zero de novo e agora foi kkk ele fica rodando mas da Starter, acho que é isso né ? (mas tipo, ja fazem 30min que ta rodando). Se cancelo aparece isso
![Uploading image.png…]()


E tambem, apareceu isso agora, na parte do LocalHost:
![image](https://user-images.githubusercontent.com/113647995/193160875-8c26d7c3-0fda-4c68-ba74-f0a680c78a55.png)

**Comment by BrunoFico** [comment]
Acho que a imagem deu errado no envio anterior, segue novamente:
![PRINT ERRO2](https://user-images.githubusercontent.com/113647995/193161468-1f13edcc-37fe-4cc3-8001-216aac151d8f.png)

**Comment by BrunoFico** [comment]
Ainda sobre a parte do 30min rodando, caso eu pare manualmente, aparece isso: (obs: nenhuma fez ele terminou sozinho, e o máximo que esperei foram os 30min)
![PRINT ERRO2](https://user-images.githubusercontent.com/113647995/193161804-51e958c7-70a3-48ac-9025-d698b9c9faa0.png)

**Comment by cami-la** [comment]
Brunão, fácil de resolver.
O JDBC URL que você está colocando no banco de dados está diferente do application.yml.

Dá uma conferida e me diz.

**Comment by BrunoFico** [comment]
Perfeito !! Era isso mesmo hehe ! Obrigado Camila ! Esse fim de semana pretendo terminar o projeto!
