### ISSUE TITLE
Erro ao rodar aplicação após criação do arquivo data.sql

### ISSUE THREAD

**Issue by satirioneto** [cami-la/sacola-api_IFOOD_DEV_WEEK#5]
![image](https://user-images.githubusercontent.com/68235037/193052701-d954318a-41ef-4f1b-baae-3594b86c9536.png)

A aplicação estava rodando bem até o momento em que foi criado o arquivo data.sql, depois disso ele para ao chegar nele.

**Comment by cami-la** [comment]
Maravilhaaaa. Parabéns! Está indo muito bem! 
Precisando, fico à disposição! <3
