### ISSUE TITLE
Problema em exibir caracteres do data.sql no localhost

### ISSUE THREAD

**Issue by satirioneto** [cami-la/sacola-api_IFOOD_DEV_WEEK#6]
![image](https://user-images.githubusercontent.com/68235037/193060529-41bcdb48-fef0-4b71-bf16-3391a5d118d6.png)

Os caracteres ASCII não aparecem como deveria, acredito que seja relacionado ao idioma mas não sei como resolver.

**Comment by cami-la** [comment]
Deve ser algo relacionado ao seu navegador. Tenta usar outro navegador e vê se acontece o mesmo comportamento?

**Comment by satirioneto** [comment]
Até tentei com o chrome também, deu a mesma coisa.

**Comment by cami-la** [comment]
@falvojr Pode me ajudar aqui?

**Comment by satirioneto** [comment]
Mas era só uma dúvida mesmo, não interfere em nada no aprendizado. Obrigado @cami-la !

**Comment by falvojr** [comment]
Oi @cami-la e @satirioneto, belezera?
@satirioneto talvez seja o encoding do arquivo .sql no seu SO, tenta adicionar essa configuração no seu arquivo .yaml, por favor:

```yaml
spring:
  datasource:
    sqlScriptEncoding: UTF-8
```

**Comment by cami-la** [comment]
> Mas era só uma dúvida mesmo, não interfere em nada no aprendizado. Obrigado @cami-la !

Mas vamos resolver, tenha fé! hehe
